--
-- CREATE TABLE inventory.product_inventory (
--                                              id BIGSERIAL PRIMARY KEY,
--                                              product_id BIGINT NOT NULL,
--                                              branch_id BIGINT NOT NULL,
--                                              quantity_on_hand INTEGER NOT NULL DEFAULT 0,
--                                              quantity_reserved INTEGER NOT NULL DEFAULT 0,
--                                              quantity_available INTEGER NOT NULL DEFAULT 0,
--                                              created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--                                              updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--                                              created_by VARCHAR(255),
--                                              updated_by VARCHAR(255),
--
--                                              CONSTRAINT fk_product_inventory_product FOREIGN KEY (product_id)
--                                                  REFERENCES inventory.products(id) ON DELETE CASCADE,
--                                              CONSTRAINT fk_product_inventory_branch FOREIGN KEY (branch_id)
--                                                  REFERENCES "sipms-branch".branches(id) ON DELETE CASCADE,
--                                              CONSTRAINT uk_product_inventory_product_branch UNIQUE (product_id, branch_id),
--                                              CONSTRAINT chk_product_inventory_qty_on_hand CHECK (quantity_on_hand >= 0),
--                                              CONSTRAINT chk_product_inventory_qty_reserved CHECK (quantity_reserved >= 0),
--                                              CONSTRAINT chk_product_inventory_qty_available CHECK (quantity_available >= 0),
--                                              CONSTRAINT chk_product_inventory_qty_logic CHECK (quantity_available = quantity_on_hand - quantity_reserved)
-- );
--
-- CREATE INDEX idx_product_inventory_product_id ON inventory.product_inventory(product_id);
-- CREATE INDEX idx_product_inventory_branch_id ON inventory.product_inventory(branch_id);
-- CREATE INDEX idx_product_inventory_availability ON inventory.product_inventory(quantity_available) WHERE quantity_available > 0;
--
-- COMMENT ON TABLE inventory.product_inventory IS 'Tracks real-time inventory levels for products at each branch';
-- COMMENT ON COLUMN inventory.product_inventory.id IS 'Primary key - auto-generated database ID';
-- COMMENT ON COLUMN inventory.product_inventory.product_id IS 'Foreign key to products table';
-- COMMENT ON COLUMN inventory.product_inventory.branch_id IS 'Foreign key to branches table';
-- COMMENT ON COLUMN inventory.product_inventory.quantity_on_hand IS 'Total physical stock available at the branch';
-- COMMENT ON COLUMN inventory.product_inventory.quantity_reserved IS 'Stock reserved for pending orders/transactions';
-- COMMENT ON COLUMN inventory.product_inventory.quantity_available IS 'Stock available for new orders (quantity_on_hand - quantity_reserved)';